# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main_widget.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWidget(object):
    def setupUi(self, MainWidget):
        MainWidget.setObjectName("MainWidget")
        MainWidget.resize(619, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWidget.sizePolicy().hasHeightForWidth())
        MainWidget.setSizePolicy(sizePolicy)
        MainWidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.TabWidget = QtWidgets.QTabWidget(MainWidget)
        self.TabWidget.setGeometry(QtCore.QRect(10, 0, 600, 600))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TabWidget.sizePolicy().hasHeightForWidth())
        self.TabWidget.setSizePolicy(sizePolicy)
        self.TabWidget.setObjectName("TabWidget")
        self.ConfigTab = QtWidgets.QWidget()
        self.ConfigTab.setObjectName("ConfigTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.ConfigTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.ConfigTab)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.ConfigTab)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(300, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 2, 1, 1)
        self.BatchSize = QtWidgets.QTextEdit(self.ConfigTab)
        self.BatchSize.setObjectName("BatchSize")
        self.gridLayout_2.addWidget(self.BatchSize, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.ConfigTab)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 200, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem1, 9, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.ConfigTab)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 5, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.ConfigTab)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 4, 0, 1, 1)
        self.LearnMixtureWeight = QtWidgets.QComboBox(self.ConfigTab)
        self.LearnMixtureWeight.setObjectName("LearnMixtureWeight")
        self.LearnMixtureWeight.addItem("")
        self.LearnMixtureWeight.addItem("")
        self.gridLayout_2.addWidget(self.LearnMixtureWeight, 3, 1, 1, 1)
        self.LearningRate = QtWidgets.QTextEdit(self.ConfigTab)
        self.LearningRate.setObjectName("LearningRate")
        self.gridLayout_2.addWidget(self.LearningRate, 0, 1, 1, 1)
        self.TrainStep = QtWidgets.QTextEdit(self.ConfigTab)
        self.TrainStep.setObjectName("TrainStep")
        self.gridLayout_2.addWidget(self.TrainStep, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 200, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem2, 8, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 200, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem3, 7, 1, 1, 1)
        self.Lambda = QtWidgets.QTextEdit(self.ConfigTab)
        self.Lambda.setObjectName("Lambda")
        self.gridLayout_2.addWidget(self.Lambda, 4, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.ConfigTab)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.AdanetIteration = QtWidgets.QTextEdit(self.ConfigTab)
        self.AdanetIteration.setObjectName("AdanetIteration")
        self.gridLayout_2.addWidget(self.AdanetIteration, 5, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 200, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem4, 10, 1, 1, 1)
        self.GeneratorType = QtWidgets.QLabel(self.ConfigTab)
        self.GeneratorType.setAlignment(QtCore.Qt.AlignCenter)
        self.GeneratorType.setObjectName("GeneratorType")
        self.gridLayout_2.addWidget(self.GeneratorType, 6, 0, 1, 1)
        self.Generator = QtWidgets.QComboBox(self.ConfigTab)
        self.Generator.setObjectName("Generator")
        self.Generator.addItem("")
        self.Generator.addItem("")
        self.Generator.addItem("")
        self.gridLayout_2.addWidget(self.Generator, 6, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.TabWidget.addTab(self.ConfigTab, "")
        self.OperationTab = QtWidgets.QWidget()
        self.OperationTab.setObjectName("OperationTab")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.OperationTab)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textEdit = QtWidgets.QTextEdit(self.OperationTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 300))
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_3.addWidget(self.textEdit)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.LoadCustomTest = QtWidgets.QPushButton(self.OperationTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LoadCustomTest.sizePolicy().hasHeightForWidth())
        self.LoadCustomTest.setSizePolicy(sizePolicy)
        self.LoadCustomTest.setMinimumSize(QtCore.QSize(180, 0))
        self.LoadCustomTest.setMaximumSize(QtCore.QSize(70, 16777215))
        self.LoadCustomTest.setObjectName("LoadCustomTest")
        self.gridLayout_4.addWidget(self.LoadCustomTest, 0, 0, 1, 1)
        self.Dataset = QtWidgets.QComboBox(self.OperationTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Dataset.sizePolicy().hasHeightForWidth())
        self.Dataset.setSizePolicy(sizePolicy)
        self.Dataset.setObjectName("Dataset")
        self.Dataset.addItem("")
        self.Dataset.addItem("")
        self.Dataset.addItem("")
        self.Dataset.addItem("")
        self.gridLayout_4.addWidget(self.Dataset, 1, 0, 1, 1)
        self.TestBtn = QtWidgets.QPushButton(self.OperationTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TestBtn.sizePolicy().hasHeightForWidth())
        self.TestBtn.setSizePolicy(sizePolicy)
        self.TestBtn.setObjectName("TestBtn")
        self.gridLayout_4.addWidget(self.TestBtn, 0, 2, 1, 1)
        self.TrainBtn = QtWidgets.QPushButton(self.OperationTab)
        self.TrainBtn.setObjectName("TrainBtn")
        self.gridLayout_4.addWidget(self.TrainBtn, 1, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(500, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem5, 0, 3, 1, 1)
        self.UseDefaultTest = QtWidgets.QPushButton(self.OperationTab)
        self.UseDefaultTest.setObjectName("UseDefaultTest")
        self.gridLayout_4.addWidget(self.UseDefaultTest, 0, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.TabWidget.addTab(self.OperationTab, "")
        self.PredictionTab = QtWidgets.QWidget()
        self.PredictionTab.setObjectName("PredictionTab")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.PredictionTab)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.formLayout.setObjectName("formLayout")
        self.gridLayout.addLayout(self.formLayout, 0, 0, 2, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout)
        self.TabWidget.addTab(self.PredictionTab, "")

        self.retranslateUi(MainWidget)
        self.TabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWidget)

    def retranslateUi(self, MainWidget):
        _translate = QtCore.QCoreApplication.translate
        MainWidget.setWindowTitle(_translate("MainWidget", "AdaNet"))
        self.label_4.setText(_translate("MainWidget", "Learn Mixture Weight"))
        self.label_2.setText(_translate("MainWidget", "Train Step"))
        self.BatchSize.setHtml(_translate("MainWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">32</span></p></body></html>"))
        self.label.setText(_translate("MainWidget", "Learning Rate"))
        self.label_6.setText(_translate("MainWidget", "Adanet Interation"))
        self.label_5.setText(_translate("MainWidget", "Adanet Lambda"))
        self.LearnMixtureWeight.setItemText(0, _translate("MainWidget", "False"))
        self.LearnMixtureWeight.setItemText(1, _translate("MainWidget", "True"))
        self.LearningRate.setHtml(_translate("MainWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">0.01</span></p></body></html>"))
        self.TrainStep.setHtml(_translate("MainWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">60000</span></p></body></html>"))
        self.Lambda.setHtml(_translate("MainWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">0</span></p></body></html>"))
        self.label_3.setText(_translate("MainWidget", "Batch Size"))
        self.AdanetIteration.setHtml(_translate("MainWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">3</span></p></body></html>"))
        self.GeneratorType.setText(_translate("MainWidget", "Generator Type"))
        self.Generator.setItemText(0, _translate("MainWidget", "Simple CNN "))
        self.Generator.setItemText(1, _translate("MainWidget", "Simple DNN"))
        self.Generator.setItemText(2, _translate("MainWidget", "NASNet A"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.ConfigTab), _translate("MainWidget", "Configuration"))
        self.LoadCustomTest.setText(_translate("MainWidget", "Load Custom Test Data"))
        self.Dataset.setItemText(0, _translate("MainWidget", "Please Select Dataset"))
        self.Dataset.setItemText(1, _translate("MainWidget", "MNIST"))
        self.Dataset.setItemText(2, _translate("MainWidget", "Fashion MNIST"))
        self.Dataset.setItemText(3, _translate("MainWidget", "CIFAR-10"))
        self.TestBtn.setText(_translate("MainWidget", "Predict"))
        self.TrainBtn.setText(_translate("MainWidget", "Train"))
        self.UseDefaultTest.setText(_translate("MainWidget", "Use Default Test Data"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.OperationTab), _translate("MainWidget", "Operation"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.PredictionTab), _translate("MainWidget", "Prediction"))


